resolver: lts-17.15
extra-deps:
  - git: https://github.com/juhp/simple-cmd-args.git
    commit: 0f015739e366468d43c0c8cf238b0ee322bee16d
  - git: https://github.com/juhp/cached-json-file.git
    commit: 993d81c3fd1588c9bbc90483e6ce8ccda33fb4ef
